name: Java CI with Maven

on:
  push:
    branches:
      - ca7

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml
  test:
    runs-on: ubuntu-latest
    name: unit tests
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
        cache: maven
    - name: Run unit tests
      run: mvn -B test
  bdd:
    runs-on: ubuntu-latest
    name: bdd tests
    needs: test
    steps:

    - uses: actions/checkout@v2
    - name: environment-set-up
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: tests
      run: mvn test
    - name: bdd-tests
      run: mvn -Dtest="bdd.BDDEntryPointAcceptanceTest" test
